### ISSUE TITLE
12/09/2016 - MisRCON v0.0.2 - UnicodeEncodeError

### ISSUE THREAD

**Issue by b3ck** [csprance/MisRCON#1]
I get this when I run the command status;

```
MisRCON-by @Csprance
v0.0.2 - Macadocious
Type help for more options.
--------------------------

> status
Traceback (most recent call last):
  File "<string>", line 129, in <module>
  File "<string>", line 125, in main
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 1135: ordinal not in range(128)
misrcon returned -1
>  
```

I wish it worked, it looks fantastic!
-b3ck

**Comment by csprance** [comment]
This is an issue with the cli and a special character being used in someones name.

Good catch!

**Comment by b3ck** [comment]
thanks, someones name is this: ñ but other than that seems to be the only player name with a special character in it =/

Kind Regards,
-b3ck

**Comment by b3ck** [comment]
Also just to confirm all other commands work.

-b3ck

**Comment by csprance** [comment]
Let me know if https://github.com/csprance/MisRCON/releases/download/v0.0.2-macadocious/MisRCON.Setup.0.0.2.exe

Solves the issue for you. I don't have a server with a weird character name to test with. This code should work

**Comment by b3ck** [comment]
Works!!!, also just to let you know you have "TODO: Bans TAB" under the settings "TAB", I want to thank you I finally have a tool that will broadcast a message every 30 minutes, thank you, thank you!

-b3ck

**Comment by b3ck** [comment]
I don't suppose since you are a Miscreated dev you can make this tool pull the chat & damage logs live in realtime could you?

-b3ck

**Comment by csprance** [comment]
there SHOULD be a way to do that with i3d's api but it will take some work and you'll need to get an API key from them in order to grab the server logs. 

Closing this issue but feel free to open up a new issue as a feature request
