### ISSUE TITLE
Feature Request: i3D.net API connection

### ISSUE THREAD

**Issue by b3ck** [csprance/MisRCON#10]
It would be nice if you could enter in an API key from i3D.net to grab server logs in realtime.

Kind Regards,
-b3ck

**Comment by b3ck** [comment]
Here are some of the things you could add to MisRCON: [i3D.net API Document](https://customer.i3d.net/apidoc/?route=gameserver) They have so many things, you could control the server, like if I wanted the server to restart everyday at 3am, I could do that with your "Scheduled Task" feature.  =)

-b3ck

**Comment by b3ck** [comment]
If I knew anything about programming I would help, but I don't.. all I can do is hope and wish you luck my friend =)

-b3ck

**Comment by csprance** [comment]
Adding this with #12
