### ISSUE TITLE
Events View

### ISSUE THREAD

**Issue by csprance** [csprance/MisRCON#12]
## Features
* Enter API Key 
* Enter UserID
* Download/Parse/View Chatlogs
* Download/Parse/View Damage logs

Thinking that this will look similar to a text message view. On the left side is a column of steamids with there most recent "event" sorted in chronological order from most recent even

On the right side will be the events sorted in chronlogical order similar to how skype/or any mms messaging looks only when we need to display kills/bleeding/other things we just show it with a different colored chat bubble.

<img src="http://www.csprance.com/shots/2016-12-14_16-20-028f1fa747-815b-451f-9ee1-c0f19de0bb9f.png" width="500px" />

**Comment by csprance** [comment]
<img src=http://www.csprance.com/shots/2016-12-14_16-53-442e8f4dda-95c7-4c76-b894-cc64b7f4bbe4.png" width="500px" />

**Comment by b3ck** [comment]
Just wanted to say this is going to be awesome, will you be adding server control? like start, stop restart? and then allowing those actions to be added in a task? this would be ultimate if you could, you're so awesome!

-b3ck
