### ISSUE TITLE
Reoccurring Tasks Don't Work

### ISSUE THREAD

**Issue by Xi57** [csprance/MisRCON#17]
After repeated attempts, the only reoccuring Chron String that works is "1-59 * * * *". As you can imagine, there's no need to spam messages every minute. Nothing else seems to work correctly, even something as simple as "1 * * * *". I'm looking forward to figuring out how to have the program automatically send out a message every 20 minutes stating the server rules to the players. This is a great idea and I really appreciate you putting in the time to make this. Thanks. - Xi57

**Comment by b3ck** [comment]
Using this will allow that:

0,20 * * * *

Kind Regards,
-b3ck

**Comment by Xi57** [comment]
I've tried so many combinations thus far, so i'll give this a go, thanks!

**Comment by csprance** [comment]
for that you would do 

`*/20 * * * *`

https://crontab.guru/examples.html

**Comment by csprance** [comment]
Minute

**Comment by Xi57** [comment]
It seems that the Chron Strong was not the source of the message not being sent to the server, but the length of the message itself. Is there a set character limit we should be aware of? A message as short as this goes through no problem, "Msg Test Ping v2.7". But a Message containing for example, 452 characters, like the one I need to transmit the rules to new players, won't be displayed in game. Any ideas?
