### ISSUE TITLE
Another Question About Reoccurring Tasks

### ISSUE THREAD

**Issue by Xi57** [csprance/MisRCON#18]
It seems that the Chronological String was not the source of the message not being sent to the server, but the length of the message itself. Is there a set character limit we should be aware of? A message as short as this goes through no problem, "Msg Test Ping v2.7". But a Message containing for example, 452 characters, like the one I need to transmit the rules to new players, won't be displayed in game. Any ideas?

**Comment by Xi57** [comment]
I was able to reduce the character count to 349, and it seems to be working for now. Super helpful tool. Thanks for all your hard work thus far!

**Comment by csprance** [comment]
Split it into multiple messages and send them a few seconds apart is my recommendation. 

I will look into putting a character limit on the input to stop that from happening. Unless I can find a way to send more. I think it may be an http URL character limit or something

**Comment by csprance** [comment]
Related issue
https://github.com/csprance/MisRCON/issues/19
