### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by WolfWeiler** [csprance/MisRCON#20]
When I try to connect to the server, it dosn't work for me.
Using a server from i3D and i get the error message:
![2017-01-06_21h05_41](https://cloud.githubusercontent.com/assets/16751561/21731414/8646a234-d454-11e6-896c-75d69cc5a3d0.png)

**Comment by csprance** [comment]
Sounds like you're using the wrong credentials somewhere. Make sure you use the admin port and admin password and the correct ip address

**Comment by WolfWeiler** [comment]
I have tried everything, the IP from the server (written in the mail from i3D) and the ServerIP from the RCON Console->status , the Query Port and the RCON Port, the old and new password~ Did i miss something?
