### ISSUE TITLE
Empyty screen

### ISSUE THREAD

**Issue by PATAPOsha** [csprance/MisRCON#21]
Have an empy grey screen after npm start. 
![xasd](https://cloud.githubusercontent.com/assets/14761219/22483470/16fefe6a-e806-11e6-9180-7affff0f56a9.png)
It happens after pasting my steam API key to app/secrets.js :
CF564D05A58AB9447986AE159E75308C (domen is my ip)
If I put some trash, like 12324123, into secrets.js, I have infinite connecting...
![llio](https://cloud.githubusercontent.com/assets/14761219/22483896/cf7a0b0a-e807-11e6-8488-58afa3859d1b.png)
I checked workability of my key with 
http://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/?key=0ABF5B1C9CC5B0B7B3804EE7E0EAC59F&steamids=76561198357864746
it works fine from different ip's
Also tried to change key, same result

Found an error
![image](https://cloud.githubusercontent.com/assets/14761219/22486749/6ed1e136-e813-11e6-8e15-9b81e7f72d1c.png)

Should I declare some variable for that key?

Why is it necessary to create my own api key? It seems to me that in previos versions there was only dev's key...

**Comment by csprance** [comment]
file should look like this
```
/**
 * Name: Contains all the secret info that shouldn't be tracked by github. This file is added to gitignore.
 * Author: Chrissprance
 * Creation Date: 12/18/2016
 * Description:
 */
export const apiKey = "API_KEY_HERE";
export const loginInfo = {"port":"port","password":"pass","ip":"IP.ADD.RESS"};
export const chatLogPath = "";
export const damageLogPath = "";
```

**Comment by csprance** [comment]
Closing this, let me know if you need additional help getting it started
