### ISSUE TITLE
Greetings from Russia to the Python

### ISSUE THREAD

**Issue by Xpomocoma** [csprance/MisRCON#24]
You need to add localization to the python. Otherwise, you can send text only in English through the command sv_say. And for the Russian community it is not very convenient. As for other communities.

**For transcoding, you need to forcely transcode the file.
`# - * - coding: cp1251 - * -`
Either create in the encoding utf-8**

Could you work a little in this direction? This is very interesting and will be necessary for everyone.

**Comment by csprance** [comment]
Create a pull request and I'll merge it in

**Comment by csprance** [comment]
I'm moving away from the python and the misrcon_cli.exe in general so this shouldn't be an issue in the next release
