### ISSUE TITLE
Lock up on log in to my server

### ISSUE THREAD

**Issue by LogicHatesCoding** [csprance/MisRCON#36]
**Describe the bug**
When I try to log into my servers MisRCON, it fails to respond, fails to close without going into task manager and even though i can move the window it will not allow me to change the window size.

**To Reproduce**
Any attempt to login. Even after a computer restart and a MisRCON re-install.

**Expected behavior**
It appears I *should* be able to login but it' "locks up."

**Screenshots**
Nothing visually extraordinary.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Chrome
 - Version: 0.2.3

**Additional context**
I was trying to set up recurring crons.

**Comment by csprance** [comment]
Sounds like you solved this issue. 

I'm closing this because v3 will solve a lot of issues and I won't be working on the old version anymore.
