### ISSUE TITLE
Build failed in reason of module types

### ISSUE THREAD

**Issue by EdgarJensonHaynes** [csprance/MisRCON#38]
Hey guys, I have a little problem with the installation of MisRCON:

When I tried 'npm run build' I got a compiler error in reason of the missing module 'types' in 
getAllServerData.js. Also I think it is a bug.

Full error message:
ERROR in ./~/node-misrcon/dist/getAllServerData/getAllServerData.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../MisRCON/node_modules/node-misrcon/dist/getAllServerData
 @ ./~/node-misrcon/dist/getAllServerData/getAllServerData.js 30:13-32

1. Download MisRCON with Ubuntu 18.04
2. npm install
3. npm run build

When I delete line 30 in getAllServerData.js the error disappears, but obviously MisRCON doesnt work proper without 'types'.

**Comment by csprance** [comment]
The README.md details why this happens. You are missing a secrets.js file in app/secrets.js
