### ISSUE TITLE
Connection Issue with Nitrado Server

### ISSUE THREAD

**Issue by ScarletYung** [csprance/MisRCON#49]
**Connection Failed**
Cant connect to my Nitrado server with the app (MisRCON), says Connection Failed while testing connection.

Desktop:

OS: Windows 10 64bit
MisRcon 3.0.4

sv_servername=Deez-PVE
http_password=***
sv_motd=***
sv_url=https://server.nitrado.net
sv_noBannedAccounts=1
sv_maxuptime=24
sv_msg_conn=1
sv_msg_death=1
g_pinglimit=1000
g_pingLimitTimer=15
g_gameRules_Camera=0
wm_disable=0
wm_timeScale=1
wm_timeScaleWeather=1
wm_timeScaleNight=5
wm_timeOffset=0
wm_forceTime=0
g_gameRules_bases=2
g_playerInfiniteStamina=1
asm_disable=0
asm_percent=33
asm_maxMultiplier=5
asm_hordeCooldown=900
pcs_maxCorpses=20
pcs_maxCorpseTime=1200
steam_inventory_enable=0
g_playerHealthRegen=0.111
g_playerFoodDecay=0.2777
g_playerFoodDecaySprinting=0.34722
g_playerWaterDecay=0.4861
g_playerWaterDecaySprinting=0.607638
g_craftingSpeedMultiplier=5

i entered all the info from my Nitrado page info about the servers, but still got the error.

**Comment by Spafbi** [comment]
If you're getting a *Connection Failed* message then you are likely looking at one of two things: you entered the incorrect IP or RCON port, or the networking requirements have not been met (the TCP port for RCON must be properly forwarded and/or opened on the firewall). MisRCON is agnostic to who is hosting the server, but correct information must be provided to MisRCON and proper network configuration is required on the part of whoever is hosting the server.

**Comment by ScarletYung** [comment]
can we discut on discord? i got a couple questions about it cuz i think it not installed correctly....

**Comment by ScarletYung** [comment]
i get a <400 error> trying to connect, and with the firewall i dont understand cause its a Nitrado server how could i access to the firewall?

**Comment by Spafbi** [comment]
You wouldn't manage Nitrado's firewall, and if you feel the server or firewall is not set up properly you would need to reach out to Nitrado's support. Feel free to join the official [Miscreated Discord server](https://discord.gg/miscreated) and ask for help in the #server-admin-help channel, too, but unless you've absolutely got the correct IP, RCON port, and password values then nobody there (or here) will be able to assist you.
