### ISSUE TITLE
Bug: Scrollbar overlapping and clipping

### ISSUE THREAD

**Issue by b3ck** [csprance/MisRCON#7]
When you have more than 12 players on your server the players tab produces a scroll bar, that scroll bar overlaps the "Scheduled Tasks" area.  See screenshot below:

![Image of overlapping scrollbar](http://i.imgur.com/sFRtEBV.png)

**Comment by csprance** [comment]
Fixed with fceda9e

**Comment by csprance** [comment]
updated the current release with the updated version 0.0.21
