### ISSUE TITLE
Bug: Recurring tasks cannot overlap

### ISSUE THREAD

**Issue by b3ck** [csprance/MisRCON#8]
It seems that if more than one task is scheduled at the same time it will only send one command to the server, this is per the log file.

Let's say I schedule one task for every 30 minutes and another task for every 2 hours, since the first scheduled task is suppose to run "every 30 minutes" which lands at the same time as the "every 2 hours" task MisRCON will only send the "every 30 minutes" task to the server.

Again this is all based off of what I can see from the log file.

Kind Regards,
-b3ck

**Comment by csprance** [comment]
This seems to be a limitation with the XMLRPC server on the actual server itself. It can only handle one connection at a time or they both fail. Will have to think on how to avoid this. For now just try to schedule it a few seconds off if possible. I'll make it so you can't schedule something at the same time.

**Comment by b3ck** [comment]
Sounds good, a warning stating that the task will overlap and to choose a different time would be helpful to new users so they don't get frustrated =)

-b3ck

**Comment by csprance** [comment]
solved in v3
